config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/kittens/:id", to: "kittens#show"

  # Defines the root path route ("/")
   root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence:true
  validates :age, presence:true
  validates :cuteness, presence:true
  validates :softness, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[ show edit update destroy ]

  # GET /kittens or /kittens.json
  def index
    @kittens = Kitten.all
  end

  # GET /kittens/1 or /kittens/1.json
  def show
    @kitten = Kitten.find(params[:id])
  end

  # GET /kittens/new
  def new
    @kitten = Kitten.new
  end

  # GET /kittens/1/edit
  def edit
    @kitten = Kitten.find(params[:id])
    render :edit
end

  # POST /kittens or /kittens.json
  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to @kitten, notice: "Kitten was successfully created." }
        format.json { render :show, status: :created, location: @kitten }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kittens/1 or /kittens/1.json
  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update(kitten_params)
    redirect_to kittens_path(@kitten)
  end

  # DELETE /kittens/1 or /kittens/1.json
  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to kittens_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: kitten) do |form| %>
  <% if kitten.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
        <% kitten.errors.each do |error| %>
          <li><%= error.full_message %></li>
          <p>Hey, I think you need some coffee!! :)</p>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness, style: "display: block" %>
    <%= form.number_field :cuteness %>
  </div>

  <div>
    <%= form.label :softness, style: "display: block" %>
    <%= form.number_field :softness %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/_kitten.html.erb
<div id="<%= dom_id kitten %>">
  <p>
    <strong>Name:</strong>
    <%= kitten.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= kitten.age %>
  </p>

  <p>
    <strong>Cuteness:</strong>
    <%= kitten.cuteness %>
  </p>

  <p>
    <strong>Softness:</strong>
    <%= kitten.softness %>
  </p>

</div>

app/views/kittens/edit.html.erb
<h1>Editing kitten</h1>

<%= render "form", kitten: @kitten %>

<br>

<div>
  <%= link_to "Show this kitten", @kitten %> |
  <%= link_to "Back to kittens", kittens_path %>
</div>

app/views/kittens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Kittens</h1>

<ul>
  <% @kittens.each do |k|%>
    <li>
    <%= link_to k.name, k %><br>
    <%= link_to "Delete", kitten_path(k), data: {
      turbo_method: :delete,
      turbo_confirm: 'Are you sure?'
      } %>
    </li><br>
  <% end %>
</ul>

<%= link_to "New kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New kitten</h1>

<%= render "form", kitten: @kitten %>

<br>

<div>
  <%= link_to "Back to kittens", kittens_path %>
</div>

app/views/kittens/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kitten %>

<div>
  <%= link_to "Edit this kitten", edit_kitten_path(@kitten) %> |
  <%= link_to "Back to kittens", kittens_path %>

  <%= button_to "Destroy this kitten", @kitten, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>